### ISSUE TITLE
ImportError: No module named decorator

### ISSUE THREAD

**Issue by andyyuan78** [val-iisc/expresso#3]
ubgpu@ubgpu:~/source_for_caffe/1/expresso$ sh run_expresso.sh
/home/ubgpu/github/expresso ROOT
Traceback (most recent call last):
  File "/home/ubgpu/github/expresso/src/main/main.py", line 49, in <module>
    import centralData
  File "/home/ubgpu/github/expresso/src/data/centralData.py", line 14, in <module>
    import dataView
  File "/home/ubgpu/github/expresso/src/data/dataView.py", line 26, in <module>
    import DataHandler
  File "/home/ubgpu/github/expresso/src/data/DataHandler.py", line 7, in <module>
    import readdb
  File "/home/ubgpu/github/expresso/src/data/readdb.py", line 9, in <module>
    import caffe
  File "/home/ubgpu/source_for_caffe/1/caffe/python/caffe/**init**.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/ubgpu/source_for_caffe/1/caffe/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "/home/ubgpu/source_for_caffe/1/caffe/python/caffe/io.py", line 4, in <module>
    from skimage.transform import resize
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/**init**.py", line 3, in <module>
    from .hough_transform import hough_circle, hough_line_peaks
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/hough_transform.py", line 3, in <module>
    from .. import measure, morphology
  File "/usr/local/lib/python2.7/dist-packages/skimage/measure/**init**.py", line 6, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "/usr/local/lib/python2.7/dist-packages/skimage/measure/_polygon.py", line 2, in <module>
    from scipy import signal
  File "/usr/lib/python2.7/dist-packages/scipy/signal/__init__.py", line 236, in <module>
    from .cont2discrete import *
  File "/usr/lib/python2.7/dist-packages/scipy/signal/cont2discrete.py", line 12, in <module>
    from .ltisys import tf2ss, ss2tf, zpk2ss, ss2zpk
  File "/usr/lib/python2.7/dist-packages/scipy/signal/ltisys.py", line 14, in <module>
    from .filter_design import tf2zpk, zpk2tf, normalize, freqs
  File "/usr/lib/python2.7/dist-packages/scipy/signal/filter_design.py", line 12, in <module>
    from scipy import special, optimize
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/**init**.py", line 148, in <module>
    from ._root import *
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/_root.py", line 20, in <module>
    from . import nonlin
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/nonlin.py", line 122, in <module>
    import scipy.sparse.linalg
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/__init__.py", line 108, in <module>
    from .isolve import *
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/**init**.py", line 6, in <module>
    from .iterative import *
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/iterative.py", line 11, in <module>
    from scipy.lib.decorator import decorator
ImportError: No module named decorator
ubgpu@ubgpu:~/source_for_caffe/1/expresso$

**Comment by andyyuan78** [comment]
fix by apt-get remove python-six
