### ISSUE TITLE
which lib of the 'Image'?  PIL, Pillow.....

### ISSUE THREAD

**Issue by andyyuan78** [val-iisc/expresso#4]
ubgpu@ubgpu:~/source_for_caffe/1/expresso$ python2 $EXPRESSO_ROOT/src/main/main.py
/home/ubgpu/github/expresso ROOT
Traceback (most recent call last):
  File "/home/ubgpu/github/expresso/src/main/main.py", line 49, in <module>
    import centralData
  File "/home/ubgpu/github/expresso/src/data/centralData.py", line 14, in <module>
    import dataView
  File "/home/ubgpu/github/expresso/src/data/dataView.py", line 26, in <module>
    import DataHandler
  File "/home/ubgpu/github/expresso/src/data/DataHandler.py", line 2, in <module>
    import Image
ImportError: No module named Image
ubgpu@ubgpu:~/source_for_caffe/1/expresso$

**Comment by andyyuan78** [comment]
fix by

ubgpu@ubgpu:~/source_for_caffe/1/expresso$ export PYTHONPATH=/usr/local/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages/PIL
